obj-y += prom.o

obj-y += mxu-v2-ex.obj

obj-$(CONFIG_XBURST_CPU_SCACHE)	+= sc.o
obj-$(CONFIG_JZ_CPU_SCACHE)	+= sc-jz.o
obj-$(CONFIG_TRAPS_USE_TCSM)	+= tcsm.o
obj-$(CONFIG_SMP)		+= smp.o smp_secondary.o ltimer.o
obj-$(CONFIG_PMON_DEBUG)	+= perf_proc_jz.o perf_event_jz.o
