
# add object if needed

obj-$(CONFIG_JZ_NONE)	+= pmon.o
obj-y			+= get-cpu-features.o
obj-y			+= proc-exec.o
obj-y			+= proc.o
obj-y			+= mxu.o
obj-y			+= jz_notifier.o
obj-$(CONFIG_JZ_NONE)	+= initrd-check.o
obj-$(CONFIG_JZ_NONE)	+= proc-pmon.o
obj-$(CONFIG_JZ_IMEM)	+= proc-imem.o
obj-$(CONFIG_JZ_NONE)	+= trace-exit.o
